name: GeneToken
columns: ["subclass", "donor_label"]
normalization: log1p
gene_sampling_strategy: random-nonzero
model_speed_sanity_check: False
precomp_embs_key: null
dataset:
  train:
    max_tokens: 1000
    variable_size: False
    panel_overlap: False
    panel_selection: mixed
    panel_selection_mixed_prob: 0.5
    panel_filter_regex: ".*"
    panel_size_min: 400
    panel_size_max: 5000
    anchor_panel_size: 40000
    anchor_max_tokens: 100
    panel_max_drop_rate: null
    feature_max_drop_rate: null
  val:
    same:
      max_tokens: ${datamodule.dataset.train.max_tokens}
      variable_size: ${datamodule.dataset.train.variable_size}
      panel_overlap: ${datamodule.dataset.train.panel_overlap}
      panel_selection: ${datamodule.dataset.train.panel_selection}
      panel_selection_mixed_prob: ${datamodule.dataset.train.panel_selection_mixed_prob}
      panel_filter_regex: ${datamodule.dataset.train.panel_filter_regex}
      panel_size_min: ${datamodule.dataset.train.panel_size_min}
      panel_size_max: ${datamodule.dataset.train.panel_size_max}
    within_P200_B256:
      max_tokens: 200
      variable_size: False
      panel_selection: random
      panel_size_min: 200
      panel_size_max: 200
    within_P800_B256:
      max_tokens: 800
      variable_size: False
      panel_selection: random
      panel_size_min: 800
      panel_size_max: 800

#PERSONALIZED PANELS!
    within_ZengGenePanel:
      max_tokens: 500
      variable_size: False
      panel_selection: preselected
      panel_filter_regex: "ZengGenePanel"
      panel_size_min: 500
      panel_size_max: 500
    within_Lipid-Met500:
      max_tokens: 500
      variable_size: False
      panel_selection: preselected
      panel_filter_regex: "Lipid-Metabolism-500_CP1275"
      panel_size_min: 500
      panel_size_max: 500
    within_Aging-SFO:
      max_tokens: 499
      variable_size: False
      panel_selection: preselected
      panel_filter_regex: "Aging-SFO_C2P2329"
      panel_size_min: 499
      panel_size_max: 499
    within_ISD:
      max_tokens: 948
      variable_size: False
      panel_selection: preselected
      panel_filter_regex: "ISD."
      panel_size_min: 948
      panel_size_max: 948
    within_Border-DA-Olig:
      max_tokens: 497
      variable_size: False
      panel_selection: preselected
      panel_filter_regex: "Border-DA-Oligo_CP1528s"
      panel_size_min: 497
      panel_size_max: 497
    within_MouseBrain500:
      max_tokens: 497
      variable_size: False
      panel_selection: preselected
      panel_filter_regex: "MouseBrain20220523_VA00274_500_genes"
      panel_size_min: 497
      panel_size_max: 497
    within_Zhuang-ABCA-1:
      max_tokens: 1122
      variable_size: False
      panel_selection: preselected
      panel_filter_regex: "Zhuang-ABCA-1"
      panel_size_min: 1122
      panel_size_max: 1122
    within_Vizgen-Receptor:
      max_tokens: 477
      variable_size: False
      panel_selection: preselected
      panel_filter_regex: "Vizgen_Receptor_panel"
      panel_size_min: 477
      panel_size_max: 477
    within_Allen-Zeng:
      max_tokens: 1129
      variable_size: False
      panel_selection: preselected
      panel_filter_regex: "Allen_Zeng"
      panel_size_min: 1129
      panel_size_max: 1129





dataloader:
  train:
    within_group_sampling: "dataset"
    batch_size: 256
    shuffle: True
    num_workers: 4
    pin_memory: False
    drop_last: True
    num_samples: null
  val:
    same:
      within_group_sampling: ${datamodule.dataloader.train.within_group_sampling}
      batch_size: ${datamodule.dataloader.train.batch_size}
      shuffle: ${datamodule.dataloader.train.shuffle}
      num_workers: 2
      pin_memory: False
      drop_last: ${datamodule.dataloader.train.drop_last}
      num_samples: 100000
    within_P200_B256:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
    within_P800_B256:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000

    within_ZengGenePanel:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
    within_Lipid-Met500:
    
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000

    within_Aging-SFO:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000

    within_ISD:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000

    within_Border-DA-Olig:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000

    within_MouseBrain500:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000

    within_Zhuang-ABCA-1:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000

    within_Vizgen-Receptor:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000

    within_Allen-Zeng:
      within_group_sampling: "dataset"
      batch_size: 256
      shuffle: True
      num_workers: 2
      pin_memory: False
      drop_last: True
      num_samples: 100000
