name: DataModule
columns: ["subclass", "donor_label"] # include all obs keys to retrieve from dataloader
label_keys_to_monitor: ["subclass"]
batch_keys_to_monitor: ["donor_label"]
normalization: raw
gene_sampling_strategy: random-nonzero
model_speed_sanity_check: False
precomp_embs_key: null
finetune_panels: False
finetune_selection_mixed_prob: 0.25
probabilistic_panel_sampling: False
probabilistic_panel_csv: /p/scratch/cjinm16/dipippo1/projects/scConcept-1/Panels/outputs/score_panels/combined_panel_sorted_max.csv
dataset:
  train: 
    transcriptomics:
      split_key: train_transcriptomics
      max_tokens: 1000
      variable_size: False
      panel_overlap: False
      panel_selection: mixed
      panel_selection_mixed_prob: 0.25
      panel_filter_regex: ".*"
      panel_size_min: 500
      panel_size_max: 5000
      panel_max_drop_rate: 0.5
      feature_max_drop_rate: null


  
dataloader:
  train:
    transcriptomics:
        within_group_sampling: "dataset"
        batch_size: 256
        shuffle: True
        num_workers: 8
        pin_memory: True
        drop_last: True
        num_samples: null
